name: Release
on:
  push:
    tags:
      - "*.*.*"
permissions:
  contents: write
jobs:
    release:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: goreleaser/goreleaser-action@v6
          with:
              distribution: goreleaser
              version: '~> v2'
              args: release --clean
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - uses: docker/build-push-action@v3
          with:
            push: true
            tags: "${{secrets.DOCKERHUB_USERNAME}}/devops_project:${{ github.ref_name}}"
